services:
  kafka:
    image: apache/kafka:3.7.1
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - kafka-net

  db:
    image: postgres:latest
    container_name: postgres_zap
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kafka-net

volumes:
  postgres_data:
    driver: local

networks:
  kafka-net:
    driver: bridge
